# Site settings

title: Far Inn 62
email: 
description: > # this means to ignore newlines until "baseurl:"
  Far Inn 62 is located at the main enterance to Munkfors, inaugurated on the 6th of June, 2004.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://farinn62.github.io" # the base hostname & protocol for your site
twitter_username:
github_username:

# Build settings
markdown: kramdown
